name: Static Analysis
on: [push, pull_request]
permissions:
  contents: read

jobs:
  static_analysis:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false

      - name: Get dependencies
        run: |
          sudo apt-get update && sudo apt-get install gcc libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev libx11-dev xorg-dev

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3          
