name: Run test on fyne development branch every day

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

jobs:
  qa-develop:
    uses: Bluebugs/shopping/.github/workflows/fyne-qa.yml@main
    with:
      branch: develop

  qa-master:
    uses: Bluebugs/shopping/.github/workflows/fyne-qa.yml@main
    with:
      branch: master
        
  qa-v24:
    uses: Bluebugs/shopping/.github/workflows/fyne-qa.yml@main
    with:
      branch: "release/v2.4.x"
